### ISSUE TITLE
Connection Problems with the node

### ISSUE THREAD

**Issue by PIOTA89** [codepleb/inschpektor#2]
Hello, something went wrong. 

This is in the error log: 
[19/05/2019 09:03:22.119] [LOG]    Failed to fetch neighbors of own node. Request failed with status code 405

**Comment by codepleb** [comment]
Hi, thx for the feedback! Did the application crash? Did it ever work? Does inschpektor run on the same  machine as your node.

Do you know how it happened?

I'm just trying to gather as much unformation as possible to understand how this happened. :)

**Comment by PIOTA89** [comment]
Hi, 
thank you for the fast answer. The application did not crash. The inschpektor showed me some Infos about my node correctly. I installed the inschpektor on the same maschine as my node. Pls have a look at the screenshots. Maybe its an initialising problem....
![Screenshot from 2019-05-19 11-34-53](https://user-images.githubusercontent.com/50791571/57980342-d444bb00-7a2a-11e9-9111-892bb152ec32.png)
![Screenshot from 2019-05-19 11-38-09](https://user-images.githubusercontent.com/50791571/57980343-d73fab80-7a2a-11e9-9ddb-592f735c1941.png)
![Screenshot from 2019-05-19 11-38-33](https://user-images.githubusercontent.com/50791571/57980346-d9a20580-7a2a-11e9-837a-c55ede430955.png)
![Screenshot from 2019-05-19 11-39-04](https://user-images.githubusercontent.com/50791571/57980347-dc045f80-7a2a-11e9-9b8c-2befe744824b.png)

**Comment by codepleb** [comment]
It looks like the call to your node fails for some reason. Are you sure you've set it up correctly?

Did you set it up with the correct values, otherwise you can click "Reset Inschpektor" and start over again.

Just to exclude some mistakes:
- You don't switch the HTTPS to "true", even if your node is reachable over https.
- As address/endpoint you just type "localhost"

The rest of the values aren't connected to this issue. Please try that and give feedback if that helps, otherwise we have to look further into it. 👍 

Here is a video I once made, it will probably be what you need (timestamp, you don't need to watch the whole one): https://youtu.be/EjXs7kpBqjQ?t=309

**Comment by PIOTA89** [comment]
He still show me the dashboard. I followed exactly the instructions from the video, but it doesn't work. Instead the ip address, i entered localhost. I see the same parameter like above...

**Comment by codepleb** [comment]
Can you execute the following line in a terminal on the machine where inschpektor runs?

```curl http://localhost:14265 \
-X POST \
-H 'Content-Type: application/json' \
-H 'X-IOTA-API-Version: 1' \
-d '{"command": "getNodeInfo"}'```

Please tell me the result, because this seems to be where inschpektor fails to gather the info.

**Comment by PIOTA89** [comment]
This is the result: 
paul@paul-Macmini:~$ curl http://localhost:14265 \
> -X POST \
> -H 'Content-Type: application/json' \
> -H 'X-IOTA-API-Version: 1' \
> -d '{"command": "getNodeInfo"}'
{"appName":"IRI","appVersion":"1.7.0-RELEASE","jreAvailableProcessors":4,"jreFreeMemory":280429912,"jreVersion":"11.0.2","jreMaxMemory":4135583744,"jreTotalMemory":673185792,"latestMilestone":"IIANIDOXDWXIYMODKTIYLMKPHZUAIINOPDKFHNDACR9FD9SDLKBXYXZGKPGZGJZPYAVXMJNJRBLVZ9999","latestMilestoneIndex":1071802,"latestSolidSubtangleMilestone":"IIANIDOXDWXIYMODKTIYLMKPHZUAIINOPDKFHNDACR9FD9SDLKBXYXZGKPGZGJZPYAVXMJNJRBLVZ9999","latestSolidSubtangleMilestoneIndex":1071802,"milestoneStartIndex":1071192,"lastSnapshottedMilestoneIndex":1071694,"neighbors":6,"packetsQueueSize":0,"time":1558260909293,"tips":5222,"transactionsToRequest":61,"features":["snapshotPruning","dnsRefresher","zeroMessageQueue","tipSolidification","RemotePOW"],"coordinatorAddress":"EQSAUZXULTTYZCLNJNTXQTQHOMOFZERHTCGTXOLTVAHKSA9OGAZDEKECURBRIXIJWNPFCQIOVFVVXJVD9","duration":0}paul@paul-Macmini:~$ ^C
paul@paul-Macmini:~$ ^C
paul@paul-Macmini:~$

**Comment by codepleb** [comment]
Ok, this looks correct. Are you running inschpektor with sudo? I doubt that this solves the problem, but who knows. Because exactly this config "works on my machine". :)

**Comment by PIOTA89** [comment]
i started inschpektor with the command: sudo inschpektor

**Comment by codepleb** [comment]
Is your inschpektor publicly exposed? Could I access it? I might be able to gain some info from my browser devtools.

**Comment by PIOTA89** [comment]
it should be, what do you need?

**Comment by codepleb** [comment]
I mean, do you have a DNS setup like https://hans.de that I could use to reach inschpektor?

**Comment by PIOTA89** [comment]
Good question, i entered my public node address like that, piota-node.net:14265, but it didnt work. It works only via the public ip adress. I knwo this sounds a little bit confusing....

**Comment by PIOTA89** [comment]
I will run inschpektor with the public ip just a moment

**Comment by codepleb** [comment]
If you are in discord, we could also move there, because everything you write here is publicly viewable. I'm in the iota channel as codepleb.

And also on Telegram, @codepleb

**Comment by PIOTA89** [comment]
hmm now i can't login, wrong pw?

**Comment by PIOTA89** [comment]
ok

**Comment by codepleb** [comment]
Info: Turned out that the node had the `getNeighbors` call blocked. Since this is unrelated to inschpektor, I close the issue here. Thanks for the feedback!
